--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create RootBG
local RootBG = ccui.Layout:create()
RootBG:ignoreContentAdaptWithSize(false)
RootBG:setBackGroundImage("res/background.jpg",0)
RootBG:setClippingEnabled(false)
RootBG:setBackGroundColorType(1)
RootBG:setBackGroundColor({r = 150, g = 200, b = 255})
RootBG:setTouchEnabled(true);
RootBG:setLayoutComponentEnabled(true)
RootBG:setName("RootBG")
RootBG:setTag(4)
RootBG:setCascadeColorEnabled(true)
RootBG:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(RootBG)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1334.0000, height = 750.0000})
Scene:addChild(RootBG)

--Create sp_logo_3
local sp_logo_3 = cc.Sprite:create("res/sp_logo.png")
sp_logo_3:setName("sp_logo_3")
sp_logo_3:setTag(5)
sp_logo_3:setCascadeColorEnabled(true)
sp_logo_3:setCascadeOpacityEnabled(true)
sp_logo_3:setVisible(false)
sp_logo_3:setPosition(667.0000, 562.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(sp_logo_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7500)
layout:setPercentWidth(0.0345)
layout:setPercentHeight(0.0613)
layout:setSize({width = 683.0000, height = 264.0000})
layout:setLeftMargin(644.0000)
layout:setRightMargin(644.0000)
layout:setTopMargin(164.5000)
layout:setBottomMargin(539.5000)
sp_logo_3:setBlendFunc({src = 1, dst = 771})
Scene:addChild(sp_logo_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

