local tm = require "testModel"
local Scheduler = tm:LSchedulerCell()
local tab = {a = "123q234",c = "dsfsd"}
print(Scheduler:testmap(tab))
print(Scheduler:testmap({a=1,b=100,c=100,f = 124},true))
Scheduler:setHandlerBack(function (id,dt,...)
	print(id,dt,...)
end)
Scheduler:setTimer(200,true)
local db = tm:SJH_DB_SQL_DBTaskEvent()
db:Run()
db:setLuaBack(function ( ... )
	--print(...)
end,function ( ... )
	print(...)
end,function ( ... )
	print(...)
end,function ( ... )
	print(...)
end)
db:push("Driver={sql server};server=47.75.78.46;uid=sa;pwd=shu110SHUsa;database=ply_web","ply_web")
db:push("select * from Area ")